### ISSUE TITLE
License

### ISSUE THREAD

**Issue by SpirinEgor** [EQuiw/code-imitator#2]
Hi!

Thank you for your amazing work, this repo is very useful for making code transformation.
I'm working on a similar project for finding code clones and I need to perform data augmentation that can be done with these transformations and some new ones. I'd like to use part of your code, but there is no license that would allow me to do it. So, I'm just wondering if you can add this, or is it done on purpose?

**Comment by EQuiw** [comment]
I've added the license. Thanks for pointing out the missing license information.
